### ISSUE TITLE
Error: Error while evaluating expression: String index is out of range

### ISSUE THREAD

**Issue by lloydwilke** [nbuchwitz/icingaweb2-module-map#102]
critical/config: Error: Error while evaluating expression: String index is out of range
Location: in /etc/icinga2/zones.d/global-templates/functions.conf: 9:13-9:32
/etc/icinga2/zones.d/global-templates/functions.conf(7): globals.getHostGeoLocation = function(hostName) {
/etc/icinga2/zones.d/global-templates/functions.conf(8):   /* XXX: Use your own name pattern and extract the location */
/etc/icinga2/zones.d/global-templates/functions.conf(9):   var loc = hostName.substr(0,4)
                                                                     ^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/zones.d/global-templates/functions.conf(10): 
/etc/icinga2/zones.d/global-templates/functions.conf(11):   if (!GeoLocationShort.contains(loc)) {

## Expected Behavior
Icinga to read the first 5 characters of each hostname and get the correct result

## Current Behavior
Index out of bounds exception

## Steps to Reproduce (for bugs)
functions.conf

```
globals.getHostGeoLocation = function(hostName) {
  /* XXX: Use your own name pattern and extract the location */
  var loc = hostName.substr(0,4)

  if (!GeoLocationShort.contains(loc)) {
    log(LogWarning, "globals.getHostGeoLocation", "Cannot find '" + loc + "' in GeoLocationShort")
    return null
  }

  var loc_idx = GeoLocationShort[loc]
  log(LogDebug, "globals.getHostGeoLocation", "Evaluating host " + hostName + " and location " + loc + " (" + loc_idx + ") ")

  if (!GeoLocation.contains(loc_idx)) {
    log(LogWarning, "globals.getHostGeoLocation", "Cannot find '" + loc_idx + "' in GeoLocation")
    return null
  }

  return GeoLocation[loc_idx]
}
```

## Context
icinga wont start up.

## Your Environment

* Icinga Web 2 Map version (System - About): 1.0.4
* Icinga Web 2 version and modules (System - About): 2.8.2
* Version used (`icinga2 --version`): 2.8.2
* Operating System and version: Centos 7
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification perfdata
* Config validation (`icinga2 daemon -C`):

**Comment by nbuchwitz** [comment]
Looks like one of your hostnames is shorter than 5 characters. 

As this is related to your config or issues with the DSL and not to the map module, I think this question should be moved to the community forums: community.icinga.com
