### ISSUE TITLE
map proxy 

### ISSUE THREAD

**Issue by haytxy** [nbuchwitz/icingaweb2-module-map#104]
hello,

I need to configure the proxy server to get maps on the internal Icinga2 monitoring tool.
Just enabled https://tile.openstreetmap.org/ but seems it is not enough.

Could you guide me on what a missed? 
What URL should be passed on the proxy configuration?

![image](https://user-images.githubusercontent.com/79607995/123635719-47c97100-d81c-11eb-8b8c-d3c3d3f7a820.png)

![image](https://user-images.githubusercontent.com/79607995/123635757-5152d900-d81c-11eb-8174-f2918b3258e6.png)

**Comment by nbuchwitz** [comment]
Hi,

the requests use a subdomain of the URL you have whitelisted: 

![Screenshot from 2021-06-28 15-54-37](https://user-images.githubusercontent.com/9132055/123648424-3a66b380-d829-11eb-8ecd-ec7ca2d8388b.png)

So I'd suggest to allow `https://*.tile.openstreetmap.org/` or if this is not possible whitelist every subdomain (a-z) individually.

Nicolai

**Comment by nbuchwitz** [comment]
Closed due to inactivity
