### ISSUE TITLE
markers not shown in current version without mapDatatype

### ISSUE THREAD

**Issue by ray-nymous** [nbuchwitz/icingaweb2-module-map#112]
hi.  i'm running map module with icinga director, but without mapDatatype.  i added a geocoords to nodes, and icons according documentation. but there are no marker or clusters shown at all. i tried to use different names of icon. from doc, from rep folder itself. tried to run it without map_icon field. but without success. markers are not shown.

please check module with latest icingaweb with director and latest php version. 

* Icinga Web 2 Map version 1.1.0
* Icinga Web 2.11.1
* archlinux
* Disabled features: command compatlog debuglog elasticsearch gelf graphite icingadb ido-pgsql influxdb opentsdb statusdata Enabled features: api checker ido-mysql influxdb2 livestatus mainlog notification perfdata syslog
* PHP 8.1.8 (cli) (built: Jul  9 2022 06:10:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies

**Comment by nbuchwitz** [comment]
Is the custom var visible in the hosts detail view?

**Comment by ray-nymous** [comment]
<img width="615" alt="1" src="https://user-images.githubusercontent.com/109845706/180947387-05720f07-43b2-4255-bf75-e1d2d49b3aa3.PNG">
<img width="627" alt="2" src="https://user-images.githubusercontent.com/109845706/180947403-17650e47-a387-439d-b777-12200d76e71d.PNG">

yes, it is. tried with extension and without it. folder /icingaweb2/doc/style/font not was existed in my environment so i created font folder and place png icon there.

**Comment by ray-nymous** [comment]
i found the reason. it was Locaton instad of location in vars section. thank u for a great module. it works perfectly now
