### ISSUE TITLE
Support for icingadb

### ISSUE THREAD

**Issue by manny4566** [nbuchwitz/icingaweb2-module-map#121]
Hello,

please add support for this module for icingadb only, without using the old monitoring module.
Thank you.

**Comment by gbin2265** [comment]
Hello,

Sukhwinder33445 doing a fantastic job making the map module work for the icingadb.

I took the latest master version and then executed the 2 pull request from sukhwinder33445.
https://github.com/nbuchwitz/icingaweb2-module-map/pull/117
https://github.com/nbuchwitz/icingaweb2-module-map/pull/116
After these modifications, the map module works for me in combination with the icingadb (old monitoring module completely stopped) when the number of hosts/services are limited.


At my request (you see the questions in the pull 116), he is now working on improving the performance for icingadb to work with a large number of hosts(6k)/services(200k).
https://github.com/nbuchwitz/icingaweb2-module-map/pull/123
This is still in development phase.

regards,
Geert

**Comment by nbuchwitz** [comment]
Released with version 2.0.0
