### ISSUE TITLE
Map Filter - IcingaDB not working

### ISSUE THREAD

**Issue by xam-stephan** [nbuchwitz/icingaweb2-module-map#125]
## Context

https://icinga2.../icingaweb2/map?_host_type=Router
![image](https://github.com/nbuchwitz/icingaweb2-module-map/assets/7057845/2d1fc8e0-7031-410b-a436-23cda2fc3c3d)

The same filter ist working with the IDO Database (both MySQL)

## Your Environment

* Icinga Web 2 Map version (System - About): 2.0.0 (GIT 0985506da55341087bf517cac07634192464a080)
* PHP: 8.0.30
* Icinga Web 2 version and modules (System - About): 2.12.1
* Version used (`icinga2 --version`): r2.14.1-1
* Operating System and version: SUSE Linux Enterprise Server 15 SP5
* Enabled features (`icinga2 feature list`): Enabled features: api checker icingadb mainlog notification perfdata
* Config validation (`icinga2 daemon -C`): Config look fine ;-)

**Comment by gbin2265** [comment]
Hello,

I think you need to convert your variable name.

_host_type=Router -> host.vars.type=Router

Information on https://icinga.com/docs/icinga-db-web/latest/doc/10-Migration/


![var_mig_icingadb](https://github.com/nbuchwitz/icingaweb2-module-map/assets/29303758/4c678952-6b3c-4d6a-a75a-8a8bada415ac)
