### ISSUE TITLE
Use a green bubble if hosts are not down

### ISSUE THREAD

**Issue by dnsmichi** [nbuchwitz/icingaweb2-module-map#13]
If 1 out of 6 hosts is red, there is no map indicator that there are even hosts on the map. This makes it hard to scroll the main map to see where my hosts are located.

Only if I know that I have hosts defined in SFO, I can click there to make the cluster view visible again.

Maybe it makes sense to change the color bubble to green instead of red for alerts then.

![screen shot 2017-08-07 at 16 04 54](https://user-images.githubusercontent.com/382049/29030145-66efa4fc-7b8a-11e7-9291-2c661b3ad6a7.png)
![screen shot 2017-08-07 at 16 04 46](https://user-images.githubusercontent.com/382049/29030146-66f042ae-7b8a-11e7-8beb-a1a7bc2a62f0.png)

**Comment by nbuchwitz** [comment]
Seems like bug. Newest release? Any Log message?

Looks different in my vagrant box:

![screenshot from 2017-08-07 16-42-57](https://user-images.githubusercontent.com/9132055/29031964-2de2864c-7b90-11e7-9c08-0db41a005e47.png)

**Comment by dnsmichi** [comment]
Sorry, git master some minutes ago.

```
commit 9ac620c1f851af245dbb8ddc5b72262d4b285df5
Author: Nicolai Buchwitz <nicolai.buchwitz@enda.eu>
Date:   Sun Aug 6 16:32:19 2017 +0200

    fix: hard and soft state handling
```

I meant that the cluster view is shown, but let's say, this bubble 

![screen shot 2017-08-07 at 16 54 52](https://user-images.githubusercontent.com/382049/29032306-31c649fa-7b91-11e7-96d5-444f5ef611da.png)


is not shown (because everything is green). So it is entirely missing.

**Comment by dnsmichi** [comment]
You can also reproduce this if you add new hosts which are pending. If it is only one, the blue marker is there. If you're in the cluster view (3 hosts pending), nothing is shown on the map.

Empty:
![screen shot 2017-08-07 at 16 55 56](https://user-images.githubusercontent.com/382049/29032378-7530e11e-7b91-11e7-940a-7492d6293efb.png)

Click:
![screen shot 2017-08-07 at 16 56 02](https://user-images.githubusercontent.com/382049/29032377-752d3f82-7b91-11e7-89c6-a6c65cea7b87.png)

**Comment by dnsmichi** [comment]
Getting closer. Set all hosts to green like this:

```
for (k => v in globals.GeoLocation) {

  //random number of
  var count = Math.floor(Math.random() * 10);
  if (count == 0) {
    count = 3
  }

  for (i in range(count)) {
    k = k.replace(" ", "-")
    object Host "map-server-" + k + "-" + i use (k, v) {
      //import "demo-host-template"
      check_command = "random"
      check_command = "dummy"
      vars.dummy_state = 0

      notes = "map host in " + k
      vars.geolocation = v
    }
  }
}

//map module expects services with geolocation
for (c in range(5)) {
  apply Service "map-" + c {
    check_command = "random"
      check_command = "dummy"
      vars.dummy_state = 0
    check_interval = 1m
    retry_interval = 1m
    vars.geolocation = host.vars.geolocation
    assign where host.vars.geolocation
  }
}

```

Then the map contains small numbers, but the bubble is missing (latest Chrome and Safari).

(bubble would be pending now)

![screen shot 2017-08-07 at 17 11 27](https://user-images.githubusercontent.com/382049/29032935-9a14eef6-7b93-11e7-8dd9-4d69a592009f.png)

force some checks to turn them green again.

So I figured - if a service of a host is NOT-OK, the bubble is red. Makes sense.

If really all services are green, and all hosts are green, the green bubble is there again.

![screen shot 2017-08-07 at 17 15 21](https://user-images.githubusercontent.com/382049/29033087-2616d37e-7b94-11e7-9f69-63dc5c137fdd.png)


So there's probably some faulty handling for hosts in pending unchecked state (probably use the light blue).

**Comment by nbuchwitz** [comment]
The style for the pending bubble was missing, fixed in 8cb7210

**Comment by dnsmichi** [comment]
Cool, I had the patch locally nearly too, thanks :) I will send you two different PRs for different state handling and an internal server error I've seen during debugging :)

**Comment by dnsmichi** [comment]
![screen shot 2017-08-07 at 17 54 44](https://user-images.githubusercontent.com/382049/29034738-901c3534-7b99-11e7-9d56-7e0e83ff6dfb.png)

👍
