### ISSUE TITLE
Store zoom level & center inside the URL (add to dashboard)

### ISSUE THREAD

**Issue by dnsmichi** [nbuchwitz/icingaweb2-module-map#14]
This allows you to focus dashboard dashlets. You can also add custom menu items based on the entire URL.

If you're pressing reload/F5 in your browser, you'll also get back to the centered and zoomed view you left previously.

I would for example create several dashlets which show central europe, east coast, etc. - I don't need the focus on a specific host and its city street, but a lower zoom level with other cities and countries.

![screen shot 2017-08-07 at 16 22 18](https://user-images.githubusercontent.com/382049/29030827-9ca3eca0-7b8c-11e7-8f91-410da711a3f4.png)

You can use this adapted configuration from the Vagrant boxes to test around:

```
const GeoLocation = {
  "amsterdam" = "52.370216,4.895168",
  "bangalore" = "12.971599,77.594563",
  "bangkok" = "13.756331,100.501765",
  "beijing" = "39.904200,116.407396",
  "berlin" = "52.524372,13.389856",
  "buenos aires" = "-34.603684,-58.381559",
  "kapstadt" = "-33.924869,18.424055"
  "new york" = "40.712784,-74.005941",
  "nuremberg" = "49.425409,11.079655",
  "london" = "51.507351,-0.127758",
  "los angeles" = "34.052234,-118.243685",
  "montreal" = "45.501689,-73.567256",
  "moscow" = "55.755826,37.617300",
  "new york" = "40.712784,-74.005941",
  "paris" = "48.856614,2.352222",
  "prague" = "50.075538,14.437800",
  "rio de janeiro" = "-22.906847,-43.172896",
  "san francisco" = "37.774929,-122.419416",
  "sydney" = "-33.865143,151.209900",
  "stockholm" = "59.329323,18.068581",
  "tokyo" = "35.689487,139.691706",
  "vienna" = "48.208174,16.373819",
}

for (k => v in globals.GeoLocation) {

  //random number of
  var count = Math.floor(Math.random() * 10);

  for (i in range(count)) {
    k = k.replace(" ", "-")
    object Host "map-server-" + k + "-" + i use (k, v) {
      //import "demo-host-template"
      check_command = "random"

      notes = "map host in " + k
      vars.geolocation = v
    }
  }
}

//map module expects services with geolocation
for (c in range(5)) {
  apply Service "map-" + c {
    check_command = "random"
    check_interval = 1m
    retry_interval = 1m
    vars.geolocation = host.vars.geolocation
    assign where host.vars.geolocation
  }
}
```

**Comment by nbuchwitz** [comment]
This feature is allready implemented. As written in the FAQ
```
Change default parameters per map

It's possible to change the parameters default_zoom, default_long and default_lat for a map by adding the parameters to the url:

map?default_zoom=20&default_long=13.370324&default_lat=52.500859
``` :-)

**Comment by nbuchwitz** [comment]
Ah ok. Maybe this could be done with a Action button like for adding to the dashboard (like implemented in google maps) ?

**Comment by nbuchwitz** [comment]
I've already a zoom handler, now trying to figure out how to pass the parameter tab-aware to the url. Is there any documentation of the JS-part of the icingaweb2 framework?

**Comment by dnsmichi** [comment]
Not that I know of, but maybe @thomas-gelf or @lippserd have an idea on how to proceed here. I don't want to suggest something which doesn't work well. Putting the params into the URL sounds good, but it might not be possible via JS actions.

**Comment by nbuchwitz** [comment]
I tried some hacks and found a possible solution, which needs further testing

**Comment by dnsmichi** [comment]
Will once I get my other tasks done here, thanks :)

**Comment by nbuchwitz** [comment]
I had to remove the Tabextension 'Add to dashboard' button, because it uses the Url from GET request of the Webserver (which contains no parameters until you hit the F5 Key).

As a replacement there is **a new map control**, which allows to create a new dashlet with the current view (zoom & map center)

![dashboard-button](https://user-images.githubusercontent.com/9132055/29221636-ce743e66-7ebf-11e7-85d4-a2710453be5f.png)

**Comment by dnsmichi** [comment]
Awesome :D

**Comment by nbuchwitz** [comment]
Could be closed?

**Comment by dnsmichi** [comment]
Yep. Thanks for your time, this is so much fun and joy after all these years with Icinga 👍
