### ISSUE TITLE
worst state handling: how to treat pending/unknown?

### ISSUE THREAD

**Issue by dnsmichi** [nbuchwitz/icingaweb2-module-map#16]
This code treats pending as the worst state. By default it should be

0 -> 99 -> 3 -> 1 -> 2

```
                    var worstState = 0;
                    $.each(cluster.getAllChildMarkers(), function(id, el) {
                        if(el.options.state > worstState) {
                            worstState = el.options.state
                        }
                    });
```

I don't have a good algorithm in mind, other than to simply ignore pending (99) and unknown (3) and treat them as "ok".

**Comment by nbuchwitz** [comment]
Sounds like a good makeshift. Maybe brainstorming @ OSMC hackathon will deliver a better algorithm

**Comment by nbuchwitz** [comment]
After some try and error I came up with a bit more enhanced algorithm. PENDING and UNKNOWN will now  be treated as OK as long as there are other states. If there are only UNKNOWN or PENDING states, the marker or cluster will indicate these states.

**Comment by dnsmichi** [comment]
Sounds fair, thanks a lot. Works fine here.

Example for an unknown service which would cause unknown before, but now is only warning as worst state bubble.

![screen shot 2017-08-08 at 13 19 31](https://user-images.githubusercontent.com/382049/29069707-4c765e7e-7c3c-11e7-8dab-c119f3fda49e.png)

**Comment by dnsmichi** [comment]
I can close my own issues reported, but I suggest removing the `question` label when you close it instead :)
