### ISSUE TITLE
configuring offline maps

### ISSUE THREAD

**Issue by AbdullahKh** [nbuchwitz/icingaweb2-module-map#18]
Thank you Nicolai for this nice module. Would it be possible to configure offline maps?

**Comment by nbuchwitz** [comment]
I could implement a config paramter for the url of the tile server. So you will need a local tile server with rendered tiles. If you need only a small region you could grab the tiles by hand and put them into the right folders on a webserver. 

To get an idea of what it means to build a tile server, I recommend the following blog post:
https://www.linuxbabe.com/linux-server/openstreetmap-tile-server-ubuntu-16-04
