### ISSUE TITLE
Default zoom/location redirect wrong

### ISSUE THREAD

**Issue by dnsmichi** [nbuchwitz/icingaweb2-module-map#21]
When I click on the menu to render 

/icingaweb2/map

it immediately redirects me to 

http://192.168.33.5/icingaweb2/map?default_zoom=5&default_lat=18.284520026072425&default_long=14.395242000000021

![screen shot 2017-08-15 at 19 18 03](https://user-images.githubusercontent.com/382049/29327147-7dc90906-81ee-11e7-8cc5-c761b5f334eb.png)

### Version

```
[root@icinga2 map]# git show -1
commit 1efdf88f865b1858c42ad05faff008d71718a114
Author: Nicolai Buchwitz <nicolai.buchwitz@enda.eu>
Date:   Tue Aug 15 19:13:58 2017 +0200

    fixed empty data check ref #19
```

You can reproduce this with the latest git master of the icinga2x Vagrant box.

I don't have any specific latitude or longitude values set.

**Comment by dnsmichi** [comment]
It takes some seconds until JavaScript rewrites the URL and then fires the redirect.

**Comment by nbuchwitz** [comment]
Hm. Maybe related to the newest feature with auto zooms the map to show all markers.

I'll take look ( .... git  pull && vagrant up --provision  ... :smiley: )

**Comment by nbuchwitz** [comment]
Even with a clean installation of the vagrant box everything looks fine to me. Have you specified any confuration?

**Comment by nbuchwitz** [comment]
Could you try to set the minimal zoom level to 2. In my case this helps

**Comment by dnsmichi** [comment]
On it. Just had to go home ;)

**Comment by dnsmichi** [comment]
Doesn't help.

```
[root@icinga2 modules]# cat /etc/icingaweb2/modules/map/config.ini
[map]
default_zoom = "2"
stateType = "soft"
```

... I have no idea where these exact latitude and longitude values are coming from.

**Comment by dnsmichi** [comment]
Maybe a cache problem .. how is the cache[id] calculated? Likewise, how can I clean that cache .. I would guess, this is just on the client.

Didn't you say you want to remove the URL update handling in #14 since it does not reliably work?

I'm fine with just the "add to dashboard" button which renders the URL properly :)

**Comment by dnsmichi** [comment]
Note: This does not happen with v1.0.2.

**Comment by nbuchwitz** [comment]
I think it relates to dd8aa9a where the auto zoom feature was introduced. 

To ensure, you could try the following:

```
diff --git a/public/js/module.js b/public/js/module.js                                                    
index 4866091..0d933b3 100644                        
--- a/public/js/module.js                            
+++ b/public/js/module.js                            
@@ -288,8 +288,8 @@                                  
                         if (show_host != "") {      
                             showHost(show_host);    
                             show_host = ""          
-                        } else if (!dashlet) {      
-                            zoomAll(id)             
+                        //} else if (!dashlet) {    
+                        //    zoomAll(id)           
                         }                           
                     }                               
                 }    
```

**Comment by dnsmichi** [comment]
Confirmed. Works again.

<img width="1322" alt="screen shot 2017-08-15 at 20 32 18" src="https://user-images.githubusercontent.com/382049/29330238-e63692e2-81f8-11e7-80bc-c669f3adf69a.png">
![screen shot 2017-08-15 at 20 32 13](https://user-images.githubusercontent.com/382049/29330239-e639412c-81f8-11e7-84af-9e66de1213f1.png)

**Comment by nbuchwitz** [comment]
> Didn't you say you want to remove the URL update handling in #14 since it does not reliably work?

Yeah, but found a found which works for me (since not using the php-method for adding a dashlet)

**Comment by nbuchwitz** [comment]
Ok. Could you click the arrow button and take a look if it is broken too?

**Comment by dnsmichi** [comment]
The same happens btw if I click on the zoom button manually.

![screen shot 2017-08-15 at 20 35 14](https://user-images.githubusercontent.com/382049/29330409-677cc4c0-81f9-11e7-9957-5ad5aa72472e.png)

**Comment by nbuchwitz** [comment]
Ok. This happens at my test environment only with small screen resolutions (or with docked developer console). Maybe I have to postpone this feature and release 1.0.3 without.

**Comment by dnsmichi** [comment]
I would advise to keep the master stable, for a while now at least. Users will start cloning your repo and the master, as they are used to it.

I've tried to zoom into the map (browser scale), it makes no difference where to move the center to.

![screen shot 2017-08-15 at 20 43 06](https://user-images.githubusercontent.com/382049/29330737-75051754-81fa-11e7-9ff3-660fa8efcfb3.png)

I'm on my Macbook here where the screen resolution should use the default Retina display (screen dimensions are 2784 × 1648).

**Comment by nbuchwitz** [comment]
I agree. Postponed all changes with 9264996. So everything should be functional (even with url auto updating)?

**Comment by nbuchwitz** [comment]
> I'm on my Macbook here where the screen resolution should use the default Retina display (screen dimensions are 2784 × 1648).

Pff. Only tested with crummy Thinkpad with FHD :smile:

**Comment by dnsmichi** [comment]
Hehe. I still love my idea to just git clone all the modules inside the Vagrant box and live test and diff any changes :-D

This is so sexy ❤️ 

![screen shot 2017-08-15 at 21 04 28](https://user-images.githubusercontent.com/382049/29331618-61cff0e8-81fd-11e7-8fa4-2d18b0452402.png)
