### ISSUE TITLE
Request: Add Support for Service Locations

### ISSUE THREAD

**Issue by cptnkoiz** [nbuchwitz/icingaweb2-module-map#22]
Hi, just wanted to say, that i like this module very much! Its awesome :)

It would be more awesome if could also put coordinates on a Service (For Example VPN Sites or Remote Devices that are monitored from a Different Location).

thank you!

**Comment by nbuchwitz** [comment]
Thanks!

I think a better way to implement something like that is, to define a host with a dummy check and apply all of its services to the host object:

```
object Host "remote-site" {                          
  import "generic-host"   
  check_command = "dummy"
  vars.geolocation = "55.635492,-6.126334"                            
}                                                    

apply Service "vpn-status" {                               
  import "generic-service"                           
  check_command = "my-vpn-check"
  command_endpoint = NodeName                        
  assign where host.name == "remote-site"            
}   
```

**Comment by dnsmichi** [comment]
The interface could become cluttered and unresponsive if you push many service objects as data points too.
