### ISSUE TITLE
Tiles not loading after default zoom level > 5

### ISSUE THREAD

**Issue by l0cksmith** [nbuchwitz/icingaweb2-module-map#24]
First, thanks for this great module...!

We tried to set the default latitude and longitude in the config of your module.
But everytime we set a "default zoom level" higer than five, no maps are loading.

The map we configured to our dashboard only says "Loading..." and the "big map" over the icingaweb2 menu Maps - > Hostmap is simply empty.

If there is anything which might help to solve the problem, please let me know. thank you.

## My Environment

* Icinga Web 2 Map version (System - About): v.103
* Icinga Web 2 version and modules (System - About): 212
* Version used (`icinga2 --version`): r2.5.4-1
* Operating System and version: Ubuntu 14.04.4 LTS
* Enabled features (`icinga2 feature list`): Enabled features: api checker command ido-mysql livestatus mainlog notification perfdataici

**Comment by nbuchwitz** [comment]
Could you share your config.ini? (`/etc/icingaweb2/modules/map/config.ini`) ?

**Comment by nbuchwitz** [comment]
Please also consider to update your icingaweb2 Installation as the module is only tested against version >=2.4

**Comment by l0cksmith** [comment]
Thanks for your fast response.
Ok, we'll try to update icingaweb2...

Here the config...

> [map]
default_lat = "48.105533"
default_long = "10.305176"
stateType = "soft"
default_zoom = "6"
max_zoom = "19"
min_zoom = ""
dashlet_height = ""
marker_size = ""

**Comment by nbuchwitz** [comment]
Looks like you found a bug (empty config fields should not happen). Ill provide a fix in master soon. In meantime you could simply delete the last three lines and everything should be fine.

**Comment by l0cksmith** [comment]
Ok, great. that worked.
the three empty lines always occur after saving the config in the webinterface (Configuration->Modules->Map)

thanks for your help!!

**Comment by nbuchwitz** [comment]
I digged into configuration parameter handling. It looks like newer icingaweb2 version (like current stable 2.4.1) treat empty config parameters different than older versions. So I strongly advice to update your icingaweb2 installation.

**Comment by l0cksmith** [comment]
I can confirm that the problem is solved with icingaweb2 v2.4.1.
Thanks for your support
