### ISSUE TITLE
Proposal to show display_name instead of hostname on popup

### ISSUE THREAD

**Issue by mcktr** [nbuchwitz/icingaweb2-module-map#25]
Hi,

first of all a big thanks for the nice module, I like it!

When you click on a host tile on the map then you see the hostname in the popup. I think it would be better to show the _display_name_ (when available).

Cheers

**Comment by nbuchwitz** [comment]
Hi,

thanks for your suggestion, i will include this feature in the next release (1.0.4).

Nicolai

**Comment by nbuchwitz** [comment]
The latest git master will show the display_name instead of host_name if set. I also updated the tooltip generation. Please test and report any problems. 

Nicolai

**Comment by mcktr** [comment]
Thanks for the fast fix. So far I didn't found any problems here.
