### ISSUE TITLE
Proposal more accurate gps coord

### ISSUE THREAD

**Issue by R00T88** [nbuchwitz/icingaweb2-module-map#26]
Hello,
actually gps coords are separated by comma as in documentation:

vars.geolocation = "34.052234,-118.243685"

but to be more accurate comma can be used as coords so i suggest to use a different token to split value.
For example this is the location that i'm testing 

45.498725 
9.4177993,17

Thanks

**Comment by nbuchwitz** [comment]
Hi,

i think this is an misunderstanding: The coordinates must be provided as decimal degrees, so precision will scale with more digits (6 digits ~ 11cm). Near all webbased map applications use WGS84 coordinates with the long / lat notation (for example google maps).

Nicolai

**Comment by dnsmichi** [comment]
I would only support one format for the geolocation tags. NagVis uses the same btw.
