### ISSUE TITLE
Filter by status

### ISSUE THREAD

**Issue by jorfermo** [nbuchwitz/icingaweb2-module-map#32]
Just installed this amazing plugin in our Organization and I was wondering if it's possible to have another view under the "Maps" menu for showing in the map only those hosts which have problems.

We are monitoring thousands of hosts and the overall map gets a bit noisy.

Thanks and congrats for the great job!

**Comment by nbuchwitz** [comment]
Sorry for getting back to your request so late. Currently it's not possible to filter only hosts with errors, but it might be a nice feature for the upcomming release. I'll add it to the roadmap.

**Comment by nbuchwitz** [comment]
Hi Jorge,

I just committed a first version of the problems filter to git master. If you want, you could checkout git master and test the filter by appending ``?problems=1`` to the map URL. Feedback highly appreciated :smile: 

Nicolai

**Comment by jorfermo** [comment]
I can confirm it's working
Good job!

**Comment by nbuchwitz** [comment]
Services should work also: If a host is up, but a Service on it is in a problem state it should be displayed with the filter.

If you want to display a special Service with an Marker, you should add geo geolocation var to the Service definition.

**Comment by jorfermo** [comment]
I have Services DOWN with the host UP and they are not showing in the map:

![image](https://user-images.githubusercontent.com/132133/39521773-37c36138-4e10-11e8-9401-a9d855cc5984.png)
![image](https://user-images.githubusercontent.com/132133/39521783-3fb93aca-4e10-11e8-9ebe-04ff004f1b9d.png)

**Comment by jorfermo** [comment]
Oh... my bad. Those hosts don't have geolocation info :)
