### ISSUE TITLE
URL for Host Action

### ISSUE THREAD

**Issue by cberg2048** [nbuchwitz/icingaweb2-module-map#33]
Thank you very much for this awesome module! 

I am trying to configure the 'Show on map' host action but I cannot find any documentation or figure out what the url should be to bring me to the specific host on the map.

**Comment by Mikesch-mp** [comment]
Its automaticly added to your hosts, just go to an host and you will find the link under "Actions"

![image](https://user-images.githubusercontent.com/6574967/31463719-6bbcbb78-aecf-11e7-9855-7a5a46d4450b.png)

**Comment by cberg2048** [comment]
That's what I assumed would be the case but it is not there.

**Comment by Mikesch-mp** [comment]
Did you also add geolocation var to your host?

**Comment by cberg2048** [comment]
Yes, all  hosts are showing up as expected. The only thing that I can think of is that I upgraded the module and there is a lingering configuration of some sort that I did not change/remove

**Comment by cberg2048** [comment]
I upgraded by removing the old module from /etc/icingaweb2/modules and replacing it with a clone from master

**Comment by Mikesch-mp** [comment]
Hmm normaly you put the modules under /usr/share/icingaweb2

**Comment by cberg2048** [comment]
You are correct sir. That was my issue. Thank you
