### ISSUE TITLE
Locations not shown on map

### ISSUE THREAD

**Issue by chas0rde** [nbuchwitz/icingaweb2-module-map#35]
The map does not show any hosts

## Expected Behavior

Map should show hosts with geolocation var set

## Current Behavior

Empty map is shown and .../icingaweb2/map/data/points shows error below:
```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8mb4', query was: SELECT COUNT(*) AS cnt FROM icinga_hosts AS h
INNER JOIN icinga_objects AS ho ON ho.object_id = h.host_object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_geolocation ON h.host_object_id = hcv_geolocation.object_id AND hcv_geolocation.varname = 'geolocation' COLLATE latin1_general_ci WHERE (hcv_geolocation.varvalue > '')
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/php/Icinga/Data/Db/DbConnection.php(264): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 /usr/share/php/Icinga/Data/SimpleQuery.php(649): Icinga\Data\Db\DbConnection->count(Object(Icinga\Module\Monitoring\Backend\Ido\Query\HoststatusQuery))
#6 /usr/share/php/Icinga/Data/Db/DbQuery.php(365): Icinga\Data\SimpleQuery->count()
#7 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(505): Icinga\Data\Db\DbQuery->count()
#8 /usr/share/icingaweb2/modules/map/application/controllers/DataController.php(81): Icinga\Module\Monitoring\DataView\DataView->count()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Map\Controllers\DataController->pointsAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('pointsAction')
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#15 {main}
```

## Steps to Reproduce (for bugs)

Not sure if reproduceable 
1. Install icinga2, icingaweb2 and MariaDB on ubuntu LTS 16.04.3 via apt-repository
2. add map-module as described in guide
3. add geolocation variable via icinga director to hosts
4. open map-view

## Context

Problem has initially been discussed in [https://monitoring-portal.org/index.php?thread/42042-map-module-not-showing-hosts/&postID=257176#wcf31](https://monitoring-portal.org/index.php?thread/42042-map-module-not-showing-hosts/&postID=257176#wcf31)
## Your Environment

* Icinga Web 2 Map version (System - About): 1.0.3
* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`):  r2.7.1-1
* Operating System and version: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-97-generic x86_64)
* Enabled features (`icinga2 feature list`): 
Disabled features: compatlog gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command debuglog graphite ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: sv0003.corp.grimme.com
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 6 NotificationCommands.
information/ConfigItem: Instantiated 75 Notifications.
information/ConfigItem: Instantiated 193 CheckCommands.
information/ConfigItem: Instantiated 6 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 Comment.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 4 Users.
information/ConfigItem: Instantiated 31 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by nbuchwitz** [comment]
Also discussed in https://monitoring-portal.org/index.php?thread/42042-map-module-not-showing-hosts/&postID=257407

**Comment by davekempe** [comment]
I have the same problem.
in /etc/mysql/mariadb.conf.d/50-server.cnf we have this as default:
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

I'm not sure changing the charset of the server and database is a a great idea - won't that break many other things?

There seems to be plenty of instances of latin1_general_ci in the icingaweb2 code:
root@icinga-master:/usr/share/icingaweb2# grep latin1_general_ci  * -ri|wc
    176    1058   28205
root@icinga-master:/usr/share/icingaweb2#

I don't know enough about mysql/mariadb to know if that is a good idea, or if we should pick a better lowest common denominator. 
My region is Australia btw:
root@icinga-master:/usr/share/icingaweb2# locale
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
root@icinga-master:/usr/share/icingaweb2#

**Comment by nbuchwitz** [comment]
I don't think it's a map-module related error. The encoding ``latin1`` is more or less hardcoded into icingaweb2 due to some restrictions of the IDO icinga2 model: https://github.com/Icinga/icinga2/issues/5412

@dnsmichi Do I miss or oversee something?

**Comment by dnsmichi** [comment]
I'd like to see the resources.ini file from Icinga Web 2 where the monitoring modules reads the IDO settings from.

**Comment by dnsmichi** [comment]
I just googled the mysql error and found this thread ... wondering why no-one else did?

https://monitoring-portal.org/index.php?thread/40725-syntax-error-when-searching-for-custom-variables/

**Comment by davekempe** [comment]
Sorry I didn't find that when googling the error. Not sure why.

I changed the charset of icinga_ido in /etc/icingaweb2/resources.ini from "" to "latin1" and it started working immediately. Thanks for your help @dnsmichi and @nbuchwitz .
Not sure if that will have any other impacts, but this bit is working, so thats awesome.
