### ISSUE TITLE
No grouping on last zoom level

### ISSUE THREAD

**Issue by avik78** [nbuchwitz/icingaweb2-module-map#37]
Hi,
could it be possible to have the option to _not_ group units it the very last zoom level? We have units in many geolocations close to each other, but still not at the exact spot and we would like them to be grouped (as today) in the second last zoom level, but not om the last zoom level. 

Thanks in advance.

Ole

**Comment by nbuchwitz** [comment]
Hi Ole,

i implemented a solution which should resolve your issue. Please test with the following branch archive (or checkout the git branch):
https://github.com/nbuchwitz/icingaweb2-module-map/archive/feature/configurable-cluster-zoomlevel.zip

**Comment by nbuchwitz** [comment]
Hi Ole,

any chance for testing the feature?
