### ISSUE TITLE
Hostmarker not visible on mobile 

### ISSUE THREAD

**Issue by nbuchwitz** [nbuchwitz/icingaweb2-module-map#38]
Host markers are no longer visible on mobiles. Instead only the hostname is displayed.

## Expected Behavior
Host markers should also be visible on mobile devices.

## Current Behavior
Markers aren't visible on android devices with google chrome

## Possible Solution
Find the cause and fix it

## Steps to Reproduce (for bugs)
Open the map on a mobile device with an android device with google chrome.

## Your Environment
* Icinga Web 2 Map version (System - About): git-HEAD
* Icinga Web 2 version and modules (System - About) : 2.4.2
* Version used (`icinga2 --version`): 2.8.0
* Operating System and version: Android (HTC M8 & Nexus 7 tablet)

**Comment by tagg** [comment]
I don't know if this is the same problem, but the symptoms are. Hostmarkers are not shown.

Validated on the demo Vagrant box (https://github.com/icinga/icinga-vagrant), on macOS 10.13.1, with both Chrome, Safari and Firefox browsers.

In Chrome developer tools, it shows that the URL for the marker icons is not correct:

The hostmarker url is: `http://192.168.33.5/icingaweb2/marker-icon-2x.png` and yields a 404.
The shadowmarker works fine: `http://192.168.33.5/icingaweb2/img/map/marker-shadow.png`.
It seems the `/img/map/` portion of the URL is missing.

**Comment by nbuchwitz** [comment]
Hi,

it looks like I forgot to set the correct path for the marker images for retina (&mobile) devides. Please check if with current HEAD everything works as expected.

**Comment by tagg** [comment]
Yes, current HEAD works fine now. Thanks!
