### ISSUE TITLE
Feature: Filter by host-group

### ISSUE THREAD

**Issue by BirkirFreyr** [nbuchwitz/icingaweb2-module-map#39]
Just found this extension, and love it.

However for our different use cases, would it be possible to add in some kind of filters?
At least filtering by hostgroups would benefit us greatly for our users, and we could then perhaps stop using NagVis.
Use-case: view a map of all of our seismology stations vs viewing a map of gps stations across the country. viewing both at the same time could get pretty cluttered pretty fast.

Thanks for this module, from the Icelandic Met office. ;)

**Comment by nbuchwitz** [comment]
Happy to hear that you like it. :+1: 

Actually you could apply most of the filters you could use in the monitoring module. It's still needs some documentation. Hostgroup filtering is some kind of tricky if you're using postgres as your backend (fixed some dayes ago. -> #29). If you're using mysql it should work as expected. Just append the filter to the url:

``/icingaweb2/map?hostgroup=my-hostgroup`` or ``/icingaweb2/map?hostgroup_name=MyHostgroupName``

You could also filter by other attributes like hostnames or custom variables.

**Comment by BirkirFreyr** [comment]
Fantastic, this should do the trick for now.
Thanks for the quick response.

**Comment by nbuchwitz** [comment]
I added some lines of documentation and also mentioned usage of filters in #46
