### ISSUE TITLE
Provides additional marker images for retina displays

### ISSUE THREAD

**Issue by nbuchwitz** [nbuchwitz/icingaweb2-module-map#42]
As seen in #38 newer leaflet versions will need an explicit retina image. For now we'll use the normal marker images for normal & retina displays, but should keep in mind that new images (marker-2x-COLOR) have to be created.

**Comment by icinga2** [comment]
Hi Nicolai,
many thank's for your work! my icingaweb2/director is using your map module. 
i would be glad if it's possible next time to set different marker images for different devices.
currently is the map only for our printer locations.
best regards, 
Karsten

**Comment by nbuchwitz** [comment]
Hi Karsten,

could you please open a new issue with this feature request? I'm already playing with a similar feature for the next release.

**Comment by nbuchwitz** [comment]
Should be obsolete with 216eba4dff82af22883e91402a7e548dfd0e8be2
