### ISSUE TITLE
Allow to save filtered maps

### ISSUE THREAD

**Issue by AbdullahKh** [nbuchwitz/icingaweb2-module-map#43]
Would it be possible to create another map? and then assign different hosts for each map?

Thanks.

**Comment by nbuchwitz** [comment]
Hi Abdullah,

you could filter your map by appending most of the icingaweb2 filters. I know that there is a lack of documentation regarding the filtering. I posted a short example in #39. If you filtered your map you could a a navgation element in your profile settings with the URL.. I'm currently working on a solution to add prefiltered maps in the module tree) and will update this issue if there is anything to see.

**Comment by nbuchwitz** [comment]
Added some lines about filtering maps in #46

**Comment by nbuchwitz** [comment]
Hi Abdullah,

I implemented something to persist maps in the current master. To create a stored map, create a file named ``maps.ini`` in your map module resources folder (e.g. /etc/icingaweb2/modules/map/) like this:

```
[my_map]
default_zoom=10
host=storage*
```

To load your stored map add ``?load=my_map`` to the URL of the map (e.g. ``/icingaweb2/map?load=my_map``). I'll provide documentation for this feature soon (#56)
