### ISSUE TITLE
Marker points to incorrect location

### ISSUE THREAD

**Issue by Hipska** [nbuchwitz/icingaweb2-module-map#44]
The marker placed on the map is pointing to a wrong location at low zoom levels. This is caused by the x/y coordinates for the marker is set for the top-left position and not bottom-center, which would be ideal in these situation.

## Expected Behavior
Take into account the dimensions of the marker and where it is pointing to.

## Current Behavior
Marker top-left is placed to the given GEO coordinates.

## Possible Solution
measure size of marker and add to x/y coordinates of where to put it on the map.

**Comment by nbuchwitz** [comment]
Hi,

tried to reconstruct the issue, but wasn't able to do so. Which browser, resolution and version of the map module do you use?

**Comment by Hipska** [comment]
Map 1.0.3 on Safari, I don't think resolution matters. The same happens with Chrome and Firefox.

Zoomed out, the marker looks placed somewhere on the French-Belgian border. 
![screenshot 2018-01-03 10 20 47](https://user-images.githubusercontent.com/228588/34514883-c97bdb2c-f06f-11e7-8a81-76b5e94a950a.png)
While zooming in reveals that it actually is placed somewhere in Bruges, which is still not (completely) correct.
![screenshot 2018-01-03 10 21 29](https://user-images.githubusercontent.com/228588/34514895-e1b670da-f06f-11e7-85c8-bc99a570851c.png)

**Comment by nbuchwitz** [comment]
Please try the latest 1.0.4 release.  Could you also post we the geolocation coordinates for the example marker?

**Comment by Hipska** [comment]
Didn't see there was a new version in the meantime. 1.0.4 seems to fix this issue.
