### ISSUE TITLE
Other options for filtering in config file

### ISSUE THREAD

**Issue by DeHook** [nbuchwitz/icingaweb2-module-map#45]
Hello,

is there a possibility to have more than one geolocation.conf file? Our concept for the server names is different for the server in our country and the international server. So we have to build two filters.

1. for international servers
globals.getHostGeoLocation = function(hostName) {
  var loc = hostName.substr(3,3)

2. for national servers
globals.getHostGeoLocation = function(hostName) {
  var loc = hostName.substr(0,3)

is there a way to link these filters or a possibility to use placeholder like "*" or something like this.

Or could it be possible to filter thorugh ip-address ranges. would it be a big effort to change those things?

Thank you very much and keep doing those nice work!

**Comment by nbuchwitz** [comment]
Hi,

your issue isn't an issue of the map module. The definition of the custom var is configured in your icinga2 configuration. Please have a look into the [icinga2 documentation (language reference)](https://www.icinga.com/docs/icinga2/latest/doc/17-language-reference/) or use the community channels like the [monitoring portal](https://monitoring-portal.org/cms/)
