### ISSUE TITLE
module-map behind proxy

### ISSUE THREAD

**Issue by jelayeb** [nbuchwitz/icingaweb2-module-map#48]
is it possible to use the module behind proxy with auth??

## Your Environment

* Icinga Web 2 Map version (System - About): 1.0.4
* Icinga Web 2 version and modules (System - About): 2.5.0
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: Centos7
* Enabled features (`icinga2 feature list`): api checker command compatlog graphite ido-mysql livestatus mainlog notification statusdata

**Comment by nbuchwitz** [comment]
Should be no problem as long you have setup the proxy in your local browser as the map only loads ressources via http?

**Comment by jelayeb** [comment]
it doesnt work with me, if it is the same as nagvis, it require proxy setting from the server side, as i used to use nagvis for openstreet maps, and i had to configure proxy for it.

**Comment by nbuchwitz** [comment]
Hm, strange. Every external resources are loaded clientside by using javascript. Could you check your browser console for any errors (F12 in google chrome)?

**Comment by jelayeb** [comment]
it worked here, i dont know what was the issue, but when i checked it next day i found it works. 
i think it was client side issue as you mentioned. 
we can close this ticket
