### ISSUE TITLE
Unable to filter hosts on map

### ISSUE THREAD

**Issue by Damien750** [nbuchwitz/icingaweb2-module-map#50]
Hello,
Thanks fo this beautiful plugin!

In the doc, you mention the fact it is possible to filter host objects on the map. However, when I add filters (for instance "http://monitoring.myserver.com/map?hostgroup=myhostgroup") in the URL, nothing seems to be filtered: I still see all of my hosts. 

Can you reproduce this problem on your side, or did I miss something?

I'm working with:
- Icinga2 r2.8.0-1
- Icinga Web 2 2.5.0
- Map module 1.0.4

Icinga is installed on CentOS 7.4 server. Data are stored in a MariaDB 15.1 database. My browser is Google Chrome 63. 

Thanks in advance for your help.

**Comment by nbuchwitz** [comment]
Hi,

i was able to reproduce the issue and commited a bugfix. Please test again with  current GIT master :)
