### ISSUE TITLE
Map filtering in dashboards don't work

### ISSUE THREAD

**Issue by Damien750** [nbuchwitz/icingaweb2-module-map#51]
I Nicolai,

Thanks again for your quick fix on map filters. I am now trying to add the filtered maps on dashboards, but can't get it to work: I always see all of my hosts.

Here are the steps to reproduce:
- Filter a map in "Maps > Host map"
- Add the filtered map to a dashboard (existing or not)

At first, filter seems to work. But if you leave the dashboard and return on it, the filter is not applyed and you see all of your hosts in the dashlet.

If you try to directly create a dashlet with a "filtered" URL (for instance "http://monitoring.myserver.com/map?hostgroup=myhostgroup"), the map is not filtered.

Can you reproduce it?

I'm working with:
- Icinga2 r2.8.1-1
- Icinga Web 2 2.5.0
- Map module 1.0.4

Icinga is installed on CentOS 7.4 server, up to date. Data are stored in a MariaDB 15.1 database. My browser is Google Chrome 63.

Thanks for your help!

**Comment by nbuchwitz** [comment]
Hi,

This is indeed a bug. I just uploaded a fix. Please test the current GIT Master and give me feedback.

**Comment by Damien750** [comment]
Hi Nicolai,
Thanks for the fix. It seems to work fine now!
