### ISSUE TITLE
additional Color Marker for handled state

### ISSUE THREAD

**Issue by wattebausch** [nbuchwitz/icingaweb2-module-map#54]
Hi Nicolai

For clusters and markers would be nice, when **worstState** consider the "handled/acknowlagement" and the color of the cluster and markers could be like icingaweb2. benefit to better see unhandled problems.

have a nice week

**Comment by nbuchwitz** [comment]
Hi,

I also want to have an indication of acknowledged / handled object, but I'm not quite sure how to do it. One way could be treating handled object as OK in the overall state calculation ... 

> color of the cluster and markers could be like icingaweb2

 What do you mean with this?

Cheers Nicolai

**Comment by wattebausch** [comment]
Hola, 

> One way could be treating handled object as OK in the overall state calculation 

For my case would be nice and will help to indicate faster unhandled problem. There is always a "but", i think a other color would be better.

> What do you mean with this?

It's hard to explain, i mean the more bright red or only the outline.
let me try to do a draw

left: from icingaweb2 on top a unacknowledged service, at the bottom, an acknowledged service.
right: an possible solution like the icingaweb2 style (in my mind)

![service-problem](https://user-images.githubusercontent.com/36966440/36961658-aa1e4762-204c-11e8-8e9c-099b4f55b2ad.png)

happy monday

**Comment by nbuchwitz** [comment]
This is also discussed in #66 and will be implemented in the the release.
