### ISSUE TITLE
character set missmach

### ISSUE THREAD

**Issue by phbu** [nbuchwitz/icingaweb2-module-map#67]
Could not fetch data from API:
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8', query was: SELECT COUNT(*) AS cnt FROM icinga_objects AS ho
 INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
 LEFT JOIN icinga_customvariablestatus AS hcv_geolocation ON h.host_object_id = hcv_geolocation.object_id AND hcv_geolocation.varname = 'geolocation' COLLATE latin1_general_ci
 LEFT JOIN icinga_customvariablestatus AS hcv_map_icon ON h.host_object_id = hcv_map_icon.object_id AND hcv_map_icon.varname = 'map_icon' COLLATE latin1_general_ci WHERE (hcv_geolocation.varvalue > '')

**Comment by nbuchwitz** [comment]
Please fix your database encoding: https://monitoring-portal.org/t/api-error-on-maps-module-startup/2250

**Comment by phbu** [comment]
thank you for the fast reply, now i converted the database and all tables to: latin1_general_ci
but i got still the same errors.

i used the following commands:
ALTER DATABASE icinga_ido CHARACTER SET latin1 CHARACTER SET latin1 COLLATE latin1_general_ci;
ALTER TABLE icinga_ido.icinga_xyz CHARACTER SET latin1 COLLATE latin1_general_ci;
the alter table cmd for all existing tables. i changed the table rows to:
`varname` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `varvalue` text CHARACTER SET latin1,

do you have any idea what the problem can be?
thank you.

**Comment by nbuchwitz** [comment]
How does your resources.ini? Which version of ``icingaweb2`` do you use? which version of the map module?

**Comment by nbuchwitz** [comment]
Could please try ``latin1`` as the charset for your IDO database. This helped in #35

**Comment by phbu** [comment]
yeah, perfect man 👍 works fine.
added: charset = "latin1"
```
[icinga_ido]
type = "db"
db = "mysql"
host = "localhost"
dbname = "icinga_ido"
username = "icinga_dat"
password = "Xea28suMHFIBrz0"
persistent = "0"
use_ssl = "0"
charset = "latin1"
```
