### ISSUE TITLE
No host/services are shown in the map

### ISSUE THREAD

**Issue by SomoIT** [nbuchwitz/icingaweb2-module-map#68]
Hi!

Using debian icinga2 installation. 
The icingaweb2 version: Package: icingaweb2 / Version: 2.4.1-1

I have installed and enabled your plugin succesfully. The map is being showed. The hosts have an action link to "Show on map". The map is displayed, but without markers.

I have configured the hosts.conf with this new server (and reloaded service afterwards) but no mark is shown:

```
object Host "TEST-SERVER" {
  import "generic-host"
  address = "192.168.190.125"
  vars.geolocation = "43.264327,-2.924130"
}
```

Am I missing something?

**Comment by nbuchwitz** [comment]
Which version of the map plugin did you try?

What is the output of ``/icingaweb2/map/data/points``?

**Comment by SomoIT** [comment]
Just downloaded:
MODULE_VERSION="1.0.4"

/icingaweb2/map/data/points ?
Sorry, what is the path? I only see the following:

```
# ls /usr/share/icingaweb2/modules/map
application  configuration.php  CONTRIBUTING.md  doc  icingaexchange.yml  library  LICENSE  module.info  public  README.md  run.php  screenshots
```

**Comment by nbuchwitz** [comment]
Sorry i wasn't clear enough :smiley: Please append /data/points to your map browser url.

Did you cloned from the git repository or did you downloaded a release file?

**Comment by SomoIT** [comment]
Thanks

Havent used git. Downloaded tar.gz.

The output you needed. Seems explicit the error jeje:
```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8mb4', query was: SELECT COUNT(*) AS cnt FROM icinga_objects AS ho
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_geolocation ON h.host_object_id = hcv_geolocation.object_id AND hcv_geolocation.varname = 'geolocation' COLLATE latin1_general_ci WHERE (hcv_geolocation.varvalue > '')
```

**Comment by SomoIT** [comment]
Solved by changing the charset (in the gui the field is empty) of the ido resource to latin1.
Configuration -> Application -> Resources...

Thanks for your help!!!
