### ISSUE TITLE
disable grouping?

### ISSUE THREAD

**Issue by blacktux** [nbuchwitz/icingaweb2-module-map#77]
Hello,

It is possible to disable the grouping of units completely? 

Would be great!

Kind regards,
André

**Comment by jediblair** [comment]
Hi - I had the same issue - you can configure the zoom level the clustering is enabled by editing the /modules/map/public/js/module.js - line ~500 at the end of the  maxClusterRadius section add a "disableClusteringAtZoom" variable - make it look approx like so - I used 10 as i only want the clustering at a high level - you can experiment with different values to suit. I think this would be a good feature to have on the configuration page actually. I haven't looked too deeply into how to do that yet. 

```
                maxClusterRadius: function (zoom) {
                    return (zoom <= map_max_zoom - 1) ? 80 : 1; // radius in pixels
                },
                disableClusteringAtZoom: 10
            });

```

**Comment by nbuchwitz** [comment]
Hi,

``disableClusteringAtZoom`` is a bit problematic, when you have markers on exat the same geolocation (like multiple hosts in one datacenter). So it's saver to override the ``maxClusterRadius`` method. I implemented in https://github.com/nbuchwitz/icingaweb2-module-map/commit/dc8d4a747a1bd373ca4dd7e6823fca3ee6b1eeda a config option, with which you can disable the clustering by setting to 1 or from a certain zoom level. I'll merge this into master soon.

Cheers Nicolai
