### ISSUE TITLE
configurable option for clustering count as number of problem hosts in the cluster rather than number of services

### ISSUE THREAD

**Issue by jediblair** [nbuchwitz/icingaweb2-module-map#78]
## Expected Behavior
I would like a configuration option for the clustering view - so that when you are looking at a clustered view, it only shows the number of hosts with issues in the circle, rather than the summary number of services. The way I'm doing things results in a large number of failed services if the host is down, so the count gets quite high with even a couple of down hosts. 

## Current Behavior
Currently only the summary number of services with issues is displayed in the red cluster icon. 

## Context

We have a board showing the map, and would rather see the number of hosts with issues than number of services. this is not a critical issue though, as I've changed the clustering display level to a higher value, so we just see a lot of markers instead of clusters at the moment. Just a nice to have.
(we're monitoring customer routers/firewalls so we have these quite spread around the map)

## Your Environment

* Icinga Web 2 Map version (System - About):
Map version 1.0.4

**Comment by nbuchwitz** [comment]
Thanks for the feature request. I implemented a config option, which should be in master soon.
