### ISSUE TITLE
Name a hosts cluster?

### ISSUE THREAD

**Issue by yaomacbt** [nbuchwitz/icingaweb2-module-map#79]
I have grouped my monitored hosts into the clusters based on their different location, on map modules. I am wondering is there a way to name the different clusters on the map? And show the clusters names on the map? 

Thanks,
Weiqi

**Comment by nbuchwitz** [comment]
Hi,

I'm afraid this is not possible in the current state as the clusters are created dynamically depending on the objects location and the zoom level. 

Nicolai
