### ISSUE TITLE
Two dashlets, only the first one gets updated

### ISSUE THREAD

**Issue by dnsmichi** [nbuchwitz/icingaweb2-module-map#9]
![screen shot 2017-08-04 at 16 14 10](https://user-images.githubusercontent.com/382049/28972449-fbace33c-792f-11e7-9e0a-11d50615a665.png)

![screen shot 2017-08-04 at 16 12 03](https://user-images.githubusercontent.com/382049/28972393-c86ce850-792f-11e7-91d4-fbf926b107f8.png)

Tested with latest Chrome and Safari.

**Comment by dnsmichi** [comment]
Oh cool, thanks :) 

Can you please create a new milestone (i.e. v1.0.1 or v1.1.0) and assign this issue to the next target? That helps keeping track of fixes and features in releases :)

@Thomas-Gelf that was the issue I was talking about :)

**Comment by nbuchwitz** [comment]
Added milestone and set due date to new release from sunday
