### ISSUE TITLE
Allways show the icon on the pin map

### ISSUE THREAD

**Issue by Procito0o** [nbuchwitz/icingaweb2-module-map#91]
Hi guys.

Have a option to hide the "0" when no have issues in clusters?, i need only show de numbers when have issues.

attach img to reference.

Sry for bad english, i'm argentian =)

![hide the zeroes](https://user-images.githubusercontent.com/28367318/58129849-16b7f480-7bf1-11e9-8411-c41e5df53e18.PNG)

**Comment by nbuchwitz** [comment]
Sorry for my late feedback. So if I'm getting you right, you want to hide all hosts with no problems and only show problems, right? This could already archived by adding appending the argument ``problems`` to your URL.

Example: ```https://monitoring.example.com/icingaweb2/map?problems```
