### ISSUE TITLE
404 in GitHub repository description

### ISSUE THREAD

**Issue by Fonata** [nbuchwitz/icingaweb2-module-map#97]
This issue is not about any file in the repository but rather the text above the file listing called "Description":  
![image](https://user-images.githubusercontent.com/6819464/78974027-593c3580-7b11-11ea-8372-55bc650f57a2.png)

The new page is https://icinga.com/docs/icinga2/latest/doc/13-addons/

**Comment by nbuchwitz** [comment]
Fixed, thanks!
