### ISSUE TITLE
IcingaDB Web Modul Error

### ISSUE THREAD

**Issue by wolf-in-sheeps-clothing** [nbuchwitz/icingaweb2-module-map#98]
On my Testmaschine I've activated IcingaDB und IcingaDB Web Modul.
Everything works fine until I activate your Map Module.

This error is shown (Host / Service):

Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php:502
Stack trace:
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php(439): Icinga\Module\Monitoring\Object\MonitoredObject->fetchHostVariables()
#1 /usr/share/icingaweb2/modules/map/library/Map/ProvidedHook/Monitoring/HostActions.php(19): Icinga\Module\Monitoring\Object\MonitoredObject->fetchCustomvars()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/HostActionsHook.php(50): Icinga\Module\Map\ProvidedHook\Monitoring\HostActions->getActionsForHost(Object(Icinga\Module\Icingadb\Compat\CompatHost))
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/ObjectActionsHook.php(21): Icinga\Module\Monitoring\Hook\HostActionsHook->getActionsForObject(Object(Icinga\Module\Icingadb\Compat\CompatHost))
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(82): Icinga\M

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

The map module itself works without problems.
I think the Problem is your Hook -> Actions -> Show on Map

(Maybe it's the globe symbol?)

Your modul -> Git Master
IcingaDB and Web Module -> 1.0.0 RC1
Icinga2 -> r2.12.0-rc1-1
Ubuntu Server 18.04.4 x64

**Comment by nbuchwitz** [comment]
Thanks for reporting. Unfortunately I don't habe any IcingaDB development environment for testing, so I could only guess that this error is implied by the breaking changes with IcingaDB.

I will try to build an IcingaDB VM for testing and have a look.

**Comment by wolf-in-sheeps-clothing** [comment]
Hi,

I found this:
Detail view produces "Uncaught Error: Call to a member function select()" when choosing an item #37

**Comment by nbuchwitz** [comment]
Could you test with the current Icingaweb GIT master esp. this PR https://github.com/Icinga/icingadb-web/commit/569b544c0c5b33e59438e5a4330553449bd813c8 ?

**Comment by wolf-in-sheeps-clothing** [comment]
OK, I've testet the fix https://github.com/Icinga/icingadb-web/pull/45

Now everything works fine!

So if you want, you could close!

**Comment by nbuchwitz** [comment]
Good to know, thanks!
