### ISSUE TITLE
Icons on Latest Master

### ISSUE THREAD

**Issue by aledr** [nbuchwitz/icingaweb2-module-map#99]
Hi.

Here is an example of icons on latest master.

![image](https://user-images.githubusercontent.com/47945/93686770-f4591400-fa8e-11ea-8b19-02b668c65772.png)

Thanks.

**Comment by aledr** [comment]
Still the same. Is this expected?

**Comment by nbuchwitz** [comment]
No, it isn't. I can't see any error on my systems. Could you please share details about your environment (please use the issue template)

**Comment by aledr** [comment]
* Icinga Web 2 Map version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.11.0 - The same happens since 2.9.2.

Loaded Libraries
icinga/icinga-php-thirdparty	0.11.0
icinga/icinga-php-library	0.9.0

Loaded Modules
audit		1.0.1
businessprocess		2.4.0
cube		1.2.0
director		1.8.1
generictts		2.0.0
grafana		1.4.2
idoreports		0.10.0
incubator		0.17.0
ipl		0.0.0
map		1.1.0
migrate		2.11.0
monitoring		2.11.0
particles		1.0.0
pdfexport		0.10.1
reporting		0.10.0
vendor		0.0.0
vspheredb		1.4.0
x509		1.1.0


* Version used (`icinga2 --version`): 2.13.2
* Operating System and version: openSUSE Leap 15.3
* Enabled features (`icinga2 feature list`): api checker command ido-pgsql influxdb2 mainlog notification

**Comment by nbuchwitz** [comment]
And which browser and version do you use? On which operating system?

**Comment by aledr** [comment]
Tested on Chrome and Firefox on Windows 10 and Windows 7.
I can provide access if you prefer.

**Comment by aledr** [comment]
@nbuchwitz any tip on how get this fixed from my side?

**Comment by nbuchwitz** [comment]
@aledr could you please check if this is fixed with the `update-libs` branch? https://github.com/nbuchwitz/icingaweb2-module-map/tree/update-libs

**Comment by aledr** [comment]
Yes! It is fixed on [update-libs](../tree/update-libs).

Thank you!

![image](https://user-images.githubusercontent.com/47945/180659124-3f5e5de5-e1d5-4262-b08b-7c45001838d6.png)
